version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: 'instala pipenv'
          command: 'pip install pipenv'
      - run:
          name: 'instala dependencias dev'
          command: 'pipenv install --dev'
      - run:
          name: 'instala dependencias'
          command: 'pipenv install'
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: 'coverage'
          command: 'pipenv run coverage run -m unittest -v'

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
